version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: perago-assignment
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: perago-user
      POSTGRES_PASSWORD: perago-passwd
      POSTGRES_DB: orga_structure